tests/unit/specs/components/__snapshots__/luxHeading.spec.js.snap, tests/unit/specs/components/luxHeading.spec.js
=> i15: bring in tests for LuxHeading component

src/components/LuxCard.vue, src/components/LuxGallery.vue, src/components/LuxMediaImage.vue, src/components/LuxTextStyle.vue, src/components/_LuxCardContent.vue, src/components/_LuxCardHeader.vue, src/components/_LuxCardMedia.vue, tests/unit/specs/components/__snapshots__/luxGallery.spec.js.snap, tests/unit/specs/components/__snapshots__/luxMediaImage.spec.js.snap, tests/unit/specs/components/__snapshots__/luxTextStyle.spec.js.snap, tests/unit/specs/components/luxGallery.spec.js, tests/unit/specs/components/luxMediaImage.spec.js, tests/unit/specs/components/luxTextStyle.spec.js
=> Add "Lux" prefix to all LUX components

package-lock.json, package.json
=> Update release script with --no-2fa flag

package.json
=> Remove --no-2fa. It is not recommended. Add --no-publish flag in np.

README.md, src/assets/styles/media_queries.scss, src/components/LuxLibraryHeader.vue, src/components/LuxMenuBar.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/menuBar.spec.js.snap, tests/unit/specs/components/menuBar.spec.js
Also includes some documentation updates
=> Migrate menu-bar component from lux

src/components/LuxLibraryHeader.vue, src/components/LuxWrapper.vue, tests/unit/specs/components/__snapshots__/luxWrapper.spec.js.snap, tests/unit/specs/components/luxWrapper.spec.js
=> Migrate the wrapper component from lux

README.md, src/components/LuxGridContainer.vue, src/components/LuxGridItem.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/luxGridContainer.spec.js.snap, tests/unit/specs/components/__snapshots__/luxGridItem.spec.js.snap, tests/unit/specs/components/luxGridContainer.spec.js, tests/unit/specs/components/luxGridItem.spec.js
=> Migrate grid components from lux

README.md, src/components/LuxLibraryHeader.vue, src/components/LuxLibraryLogo.vue, src/components/index.js
=> Add LibraryLogo component - Rename element tag for LibraryHeader - Update READme

src/components/LuxSearchBox.vue, src/components/index.js
=> Adds LuxSearchBox component

src/main.js
It is not being called when running the styleguide or when building the bundle
=> Remove main.js

package-lock.json, package.json, src/index.js, styleguide.config.js, styleguide_vue_app.js
helps with #51 , since the lux date picker depends on this plugin
=> Install the VCalendar plugin in styleguidist and the lux bundle

src/components/LuxAlert.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/luxAlert.spec.js.snap, tests/unit/specs/components/luxAlert.spec.js
=> Adds Alert Component

src/components/LuxDataTable.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/luxDataTable.spec.js.snap, tests/unit/specs/components/luxDataTable.spec.js
=> Migrate the Data Table component from lux

src/components/LuxInputButton.vue, src/components/icons/LuxIconAlert.vue, src/components/icons/LuxIconApproved.vue, src/components/icons/LuxIconAscending.vue, src/components/icons/LuxIconBase.vue, src/components/icons/LuxIconDenied.vue, src/components/icons/LuxIconDescending.vue, src/components/icons/LuxIconSearch.vue, src/components/icons/LuxIconUnsorted.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/luxDataTable.spec.js.snap, tests/unit/specs/components/__snapshots__/luxDatePicker.spec.js.snap, tests/unit/specs/components/__snapshots__/luxMenuBar.spec.js.snap, tests/unit/specs/components/luxDataTable.spec.js, tests/unit/specs/components/luxDatePicker.spec.js, tests/unit/specs/components/luxInputText.spec.js, tests/unit/specs/components/luxMenuBar.spec.js
* Bring in some more missing components
* Declare or stub child components
=> Quiet more warnings when running the test suite

src/components/LuxDatePicker.vue, tests/unit/specs/components/luxDatePicker.spec.js
=> Get date range functionality working again

src/components/LuxDatePicker.vue, src/components/LuxInputText.vue, tests/unit/specs/components/luxInputText.spec.js
Also make the LuxInputText inputfocus event consistent with the existing inputblur event
closes #84
=> Use the correct events to open/dismiss datepicker popup

src/components/LuxDropdownMenu.vue, src/components/index.js, tests/unit/specs/components/__snapshots__/luxDropdownMenu.spec.js.snap, tests/unit/specs/components/luxDropdownMenu.spec.js
=> Add LuxDropDownMenu

src/components/LuxTag.vue, tests/unit/specs/components/luxCard.spec.js, tests/unit/specs/components/luxTag.spec.js
=> Add LuxTag

src/index.js
=> Export components as named exports

src/assets/styles/system.scss
=> resolve deprecation warning for division

src/components/LuxDatePicker.vue
=> Define DatePicker's name, so that it can be registered

src/components/icons/LuxIconClock.vue, src/components/icons/LuxIconRefresh.vue, src/components/icons/LuxIconReported.vue, src/components/index.js
Resolves several warnings such as  `[Vue warn]: Failed to resolve component: lux-icon-reported`
Closes #100
=> Add icons for Approvals and Reduce console warnings

package-lock.json, package.json, src/components/LuxGridItem.vue
closes #110 
Update function round-width($i) not to add a space between the value and the % symbol #110
=> Update function round-width($i) - Update packages: sass and sass-loader

src/components/LuxAutocompleteInput.vue, tests/unit/specs/components/luxAutocompleteInput.spec.js
Helps with https://github.com/pulibrary/approvals/issues/1054
=> Declare emits for LuxAutocompleInput component

src/components/LuxDropdownMenu.vue, tests/unit/specs/components/__snapshots__/luxDropdownMenu.spec.js.snap, tests/unit/specs/components/luxDropdownMenu.spec.js, tests/unit/specs/components/luxInputButton.spec.js
part of https://github.com/pulibrary/approvals/issues/1051
=> Add emits option for luxDropDown and LuxInputButton 

src/components/LuxTextStyle.vue
Helps with https://github.com/pulibrary/approvals/issues/1048
=> Fix copy/pasta in LuxTextStyle component

src/components/LuxDropdownMenu.vue
=> Typo fix in css deep attribute fixes dropdown menu item list display

src/assets/styles/system.scss, src/components/LuxDataTable.vue, src/components/LuxDropdownMenu.vue, src/components/LuxInputButton.vue, src/components/LuxInputText.vue
keep latest sass functions from lux in one file.
Remove duplication that was overriding the correct calculation
=> keep latest sass functions from lux in one file.

src/components/_LuxCardMedia.vue
See documentation for [Slotted selectors](https://vuejs.org/api/sfc-css-features.html#slotted-selectors)
=> Use slotted to target slot content in LuxCard

src/components/LuxLibraryHeader.vue
closes https://github.com/pulibrary/approvals/issues/1066
=> Update Library Header with the correct component LuxSpacer

src/components/icons/LuxIconNote.vue, src/components/icons/LuxIconPerson.vue, src/components/icons/index.js
closes https://github.com/pulibrary/approvals/issues/1081
part of https://github.com/pulibrary/approvals/issues/1085,
=> Add lux icon person and note

src/components/icons/LuxIconArrowDown.vue, src/components/icons/LuxIconArrowRight.vue, src/components/icons/LuxIconDelivery.vue, src/components/icons/LuxIconDerivativesHealthy.vue, src/components/icons/LuxIconDerivativesUnhealthy.vue, src/components/icons/LuxIconEdit.vue, src/components/icons/index.js
part of #122 
LuxIconArrowDown,
LuxIconArrowRight,
LuxIconDelivery,
LuxIconDerivativesHealthy,
LuxIconDerivativesUnhealthy,
LuxIconEdit
=> Add more lux icons

src/components/LuxCard.vue
closes https://github.com/pulibrary/approvals/issues/1083
Bring missing css from lux
Remove reduntant css that wasn't in lux
=> Fix css syntax in lux-card

src/components/LuxInputText.vue
part of https://github.com/pulibrary/approvals/issues/1090
=> Remove slotted attribute from LuxInputText css 

src/components/LuxAutocompleteInput.vue
Fixes reference to a non existing css var
=> In LuxAutoCompleteInput use calculated local scope

package-lock.json
Just upgrading some dependency versions
=> npm upgrade

src/assets/styles/mixins.scss, src/components/LuxInputText.vue
closes https://github.com/pulibrary/approvals/issues/1121
=> Use scss vars in rgba calculation 

src/components/LuxDatePicker.vue
towards https://github.com/pulibrary/approvals/issues/1105
=> Update Datepicker functions to use the correct event

src/components/LuxDatePicker.vue
Connected to https://github.com/pulibrary/approvals/issues/1105
=> Wrap updateRangeInput function in watchEffect()

src/components/LuxAlert.vue, src/components/LuxLoader.vue, styleguide.config.js, tests/unit/specs/components/__snapshots__/luxLoader.spec.js.snap, tests/unit/specs/components/luxLoader.spec.js
- Adds LuxLoader component and tests
- Also creates a "Logos" section
- Also fixes fullscreen style for prop `type="alert"`
=> Adds LuxLoader component and tests... and more

.circleci/config.yml
=> Build the styleguide and package as part of CI

src/components/LuxLibraryLogo.vue
=> Move 0 outside margin var

src/components/logos/LuxLogoFacebook.vue, src/components/logos/LuxLogoTwitter.vue
=> Change X logo and facebook viewbox

src/components/LuxSpecialCollectionsFooter.vue, src/components/index.js
=> Add Special Collections footer component

package-lock.json, package.json, src/assets/styles/style.scss, src/assets/styles/system.scss, vite.config.js
=> Copy scss to dist and export

src/components/icons/index.js
=> Add missing icons to index.js

README.md, docs/adding_lux.md
This includes information about tree-shaking
Closes #162
=> Add instructions for adding lux to a site or application

src/assets/styles/variables.css, src/components/LuxCard.vue, src/components/LuxDisclosure.vue, src/components/icons/LuxIconArrowUp.vue, src/components/icons/index.js, src/components/index.js, tests/unit/specs/components/luxDisclosure.spec.js
Related to https://github.com/pulibrary/allsearch_frontend/issues/276
=> Add a disclosure component

package.json, src/lux-design-system.d.ts, vite.config.js
Closes #203 , although it would be nice to distribute a more descriptive .d.ts in the future.
=> Distribute a very basic .d.ts file for ease of integration into typescript apps

src/components/LuxDisclosure.vue
=> LuxDisclosure: treat icon as decorative with aria-hidden: true

.circleci/config.yml
Also, remove node 21, since it will be EOL soon.
=> Test on Node 22

src/components/LuxLibraryFooter.vue, src/components/_LuxLibraryContactInfo.vue
closes #220 
helps with https://github.com/pulibrary/static-tables/issues/126
=> [#220] Allow lux applications to import LuxLibraryFooter

src/components/LuxMenuBar.vue
=> [LuxMenuBar] Register child LuxHamburger component locally

src/components/LuxDisclosure.vue
=> [Disclosure] Don't scroll when setting focus

src/components/LuxLibraryFooter.vue, src/components/LuxLibraryLogo.vue, src/components/_LuxLibraryContactInfo.vue, src/components/_LuxUniversityAccessibility.vue, src/components/_LuxUniversityCopyright.vue, src/components/index.js, src/components/logos/LuxLogoX.vue
towards #185 
Rename twitter to x
Add default theme dark for LuxFooter
=> [#185]Update LuxFooter

src/components/LuxLibraryFooter.vue, src/components/_LuxLibraryContactInfo.vue, src/components/_LuxUniversityAccessibility.vue, src/components/_LuxUniversityCopyright.vue
part of #185 
- [#185] Fix display of Contact info component in the docs
- Update display of contact info based on the selected theme'
- [#185] Fix Accessibility display in documents
- Update Accessibility display to toggle between different themes
- [#185] Include theme shade in footer theme calculation
- Fix copyright theme display
=> 185 contact info

src/components/LuxLibraryFooter.vue, src/components/_LuxUniversityCopyright.vue
part of #185 
Fix copyright theme display
=> [#185] Include theme shade in footer theme calculation

tests/unit/specs/components/luxLibraryHeader.spec.js
=> Test the LuxLibraryHeader

src/components/LuxLibraryHeader.vue, tests/unit/specs/components/luxLibraryHeader.spec.js
- Move orange accent to bottom and make smaller
- Test slot
Connected to #216
=> Update header to match library.psb-prod

src/components/LuxLibraryFooter.vue, src/components/_LuxSubscribeNewsletter.vue, src/components/index.js, tests/unit/specs/components/luxSubscribeNewsletter.spec.js
=> [#185] Add Subscribe Newsletter internal component

src/components/LuxLibraryFooter.vue, src/components/logos/LuxLogoUniversityWhite.vue
=> [#185]Include style in logo-white svg

src/components/LuxLibraryFooter.vue, src/components/logos/LuxLogoUniversityWhite.vue
=> 185 position pu logo

src/components/LuxSpecialCollectionsFooter.vue, src/components/_LuxLibraryContactInfoOld.vue, src/components/_LuxUniversityAccessibilityOld.vue, src/components/_LuxUniversityCopyrightOld.vue, src/components/index.js
=> [#255] Special Collections footer - use old contact info component, old accessibilitty, old copyright

src/components/LuxLibraryFooter.vue
=> [LuxLibraryFooter] #185 Adjust PU logo size

src/components/_LuxSubscribeNewsletter.vue
=> [LuxLibraryFooter] #185 Update aria-label to indicate the action that the users needs to take in the input field

src/components/LuxLibraryFooter.vue
Import LuxSubscribeNewsletter; 
Import LuxLibraryLogo
=> [LuxLibraryFooter] Import LuxSubscribeNewsletter; Import LuxLibraryLogo

src/components/LuxLibraryHeader.vue, src/components/LuxWrapper.vue
=> [LuxLibraryHeader] for screens >= 900px set max-width: 1440px;

src/components/LuxLibraryFooter.vue
=> [LuxLibraryFooter] Adjust max-width to match the WDS library web site

src/components/LuxLibraryFooter.vue, src/components/LuxLibraryLogo.vue
=> [LuxLibraryFooter] match logo size to the WDS library website footer logo

src/components/LuxLibraryFooter.vue
=> Imitate the inline layout borders from the new library website footer

src/components/LuxLibraryFooter.vue, src/components/LuxWrapper.vue
=> [LuxLibraryFooter] For @media (min-width: 900px) set max-width: 1440px to follow the new Library website settings

src/components/LuxMenuBar.vue
Part of pulibrary/allsearch_frontend#316
=> [LuxMenuBar] consistent font size with WDS library website

src/assets/styles/focus.scss, src/components/LuxLibraryFooter.vue, src/components/LuxLibraryHeader.vue, src/components/LuxLibraryLogo.vue, src/components/LuxMenuBar.vue, src/components/_LuxLibraryContactInfo.vue, src/components/_LuxUniversityAccessibility.vue
Use new focus indicator in header and footer.
=> I250 focus in header and footer

src/components/LuxLibraryHeader.vue
Closes #294
I really wish I could figure out how to get this to resize based on media query, but I wasn't able to figure out how to do that.
=> Make header logo larger to match new website

src/components/LuxAlert.vue, tests/unit/specs/components/luxAlert.spec.js
This helps with pulibrary/allsearch_frontend#391
=> [LuxAlert] emit event when the user dismisses an alert

src/assets/styles/focus.scss, src/components/LuxLibraryFooter.vue, src/components/LuxLibraryLogo.vue, src/components/_LuxLibraryContactInfo.vue, src/components/_LuxSubscribeNewsletter.vue, src/components/_LuxUniversityAccessibility.vue
closes #305
closes #306
closes #310
- Update LuxSubscribeNewsletter-
- LuxLibraryFooter- 
- LuxAccessibility- 
- LuxLibraryContactInfo- 
- LuxLibraryLogo- 
- collapse subscribe newsletter button in very small screens max-width: 380px
- update hover helper
=> Update LuxSubscribeNewsletter- LuxLibraryFooter- LuxAccessibility- LuxLibraryContactInfo- LuxLibraryLogo- 

src/components/LuxLibraryFooter.vue, src/components/LuxLibraryLogo.vue
[LuxLibraryLogo] Keep consistent top and bottom padding in pul logo
[[LuxLibraryFooter] remove top padding from footer
=> [LuxLibraryFooter] remove top padding from footer keep consisten padding in the pul-log

src/components/LuxLibraryHeader.vue, src/components/LuxMenuBar.vue
[LuxLibraryHeader] Update to use font-size-base
[LuxMenuBar] Update to use font-size-base
=> [LuxLibraryHeader] [LuxMenuBar] Update to use font-size-base

vite.config.js
=> [#304] Update vite.config.js to generate iife file

docs/adding_lux.md
=> Document how to include a script src IIFE file

src/components/index.js
I forgot to do this in #323 -- sorry about that
=> Add _LuxMenuBarLabel for export

README.md, docs/lux_usage.md
I just thought this would be fun!
=> Add a list of applications and sites that use lux

styleguide.config.js
closes #172
Thanks to @sdellis for finding this setting!
=> [#172] Display Lux version in the styleguide docs

src/components/LuxLibraryFooter.vue
=> attempting to right align some of the new footer to the header

src/components/LuxLibraryHeader.vue
=> [LuxLibraryHeader] #343 display border

src/components/LuxLibraryFooter.vue, src/components/_LuxUniversityAccessibility.vue
closes #353 
This also evens out the vertical spacing in the footer area in mobile viewports.
Screenshots:
=> Update alignment of elements in the footer.

src/components/index.js
Small follow-up to #364 -- apologies for not catching it earlier!  I only remembered when I tried running `npm run release` and it reminded me about it.
=> Export the University Footer

src/components/LuxDropdownMenu.vue, src/components/LuxMenuBar.vue, tests/unit/specs/components/__snapshots__/luxMenuBar.spec.js.snap, tests/unit/specs/components/luxMenuBar.spec.js
Advances #313. 
Closes menu when you click outside.
=> Close menu outside button bug

src/components/LuxMenuBar.vue, tests/unit/specs/components/luxMenuBar.spec.js
Closes #313
Huge thanks to @ishasinha1 for researching this issue, and for suggesting the equality comparison approach that did the trick!
=> [LuxMenuBar] Close an open menu when the user tabs out of it

src/components/LuxAutocompleteInput.vue, src/components/LuxDataTable.vue, src/components/LuxInputSelect.vue, src/components/LuxInputText.vue, src/components/LuxLoader.vue
Completes the required migration and the resulting interfaces look the same!
Closes #376
=> Migrates the SCSS variables in rgba to CSS in color-mix

src/components/LuxDisclosure.vue
Fixes #342 
I was not able to recreate the error either but, this modification should prevent such errors in the future.
=> Does not try to call focus on null

docs/design_principles.md, styleguide.config.js
Closes #379 
Is it okay that I have ### inside the h3 tag? Without it, all the numbers become 1. instead of whatever the actual number should be.
=> Adds design principles to Lux

docs/adding_icons.md, styleguide.config.js
Closes #380 
* Can be used with VoiceOver in Safari
* Does not add any accessibility issues
* Style consistent with other pages
=> Adds information for adding icons

src/components/LuxUniversityFooter.vue
=> Allows for translation by passing custom links into footer as props

src/components/LuxLibraryFooter.vue, src/components/LuxLibraryHeader.vue, src/components/LuxMenuBar.vue, src/components/LuxUniversityFooter.vue
Ref #401 
This PR also cleans up some unnecessary code.
=> Fixes footer logo size 

src/components/LuxAutocompleteInput.vue, tests/unit/specs/components/luxAutocompleteInput.spec.js
=> Autocomplete dropdown now closes when there is a blur event

src/components/LuxUniversityFooter.vue
closes https://github.com/pulibrary/orangelight/issues/2878
Related issue https://github.com/pulibrary/orangelight/issues/2878#issuecomment-2688804082
=> [LuxUniversityFooter] Fix binding properties of href and text so that the links resolve

package-lock.json
Reverts pulibrary/lux-design-system#421
=> Revert "Bump the npm_and_yarn group across 1 directory with 2 updates"

package-lock.json, package.json, tests/unit/specs/components/__snapshots__/luxDatePicker.spec.js.snap, tests/unit/specs/components/__snapshots__/luxInputCheckbox.spec.js.snap, tests/unit/specs/components/__snapshots__/luxInputRadio.spec.js.snap, tests/unit/specs/components/__snapshots__/luxInputSelect.spec.js.snap, vite.config.js
=> Updates vue and modifies snapshots to ensure they pass

package-lock.json, src/components/LuxAutocompleteInput.vue, tests/unit/specs/components/__snapshots__/luxAutocompleteInput.spec.js.snap, tests/unit/specs/components/luxAutocompleteInput.spec.js
=> Autocomplete dropdown: show on click

package-lock.json
I ran `npm install`, resulting in these changes to package-lock.json.  This allows me to run `npm ci`
Closes #431
=> Fix npm ci

src/components/LuxDisclosure.vue, tests/unit/specs/components/luxDisclosure.spec.js
These changes were recommended by colleagues at the CSUN Assistive Technology Conference who graciously provided accessibility testing and feedback.
=> [LuxDisclosure] Improve documentation and add aria-describedby option

src/components/LuxSearchBox.vue, tests/unit/specs/components/luxSearchBox.spec.js
If it is placed in a search form, it needs to be able to submit the form.
=> [LuxSearchBox] Search button should have type submit

src/components/LuxSearchBox.vue, tests/unit/specs/components/luxSearchBox.spec.js
Also, slight adjustments to look and feel, and remove the placeholder in the default lux-search-box
=> [LuxSearchBox] Make input name configurable

src/assets/styles/variables.css
helps with https://github.com/pulibrary/allsearch_frontend/pull/521
color-cold-blue
space-x-larger
=> Add some new variables to support new updates in Allsearch

docs/design_tokens.md, src/assets/styles/variables.css, src/components/LuxBadge.vue
This reverts commit 8bc83315cb90008be549457083e1952c144b67da.
=> Reapply "Create a basic badge element with various color options"

src/components/LuxDisclosure.vue, src/components/LuxShowMore.vue, tests/unit/specs/components/luxShowMore.spec.js
This component is based on, and replaces, the `LuxDisclosure` component
Helps with https://github.com/pulibrary/allsearch_frontend/issues/508
=> Add a ShowMore component

src/components/LuxSearchBox.vue
This was requested by AUX in https://github.com/pulibrary/allsearch_frontend/issues/590
=> [LuxSearchBox] Remove box shadow

src/components/LuxTextStyle.vue
helps with https://github.com/pulibrary/orangelight/issues/4912
=> [LuxTextStyle] Update to use var(--color-green)

src/components/LuxTextStyle.vue
helps with https://github.com/pulibrary/orangelight/issues/4912
=> [LuxTextStyle] update colors
