pulibrary/lux-design-system

src/components/MediaImage.vue

This resolves the problem "TypeError: _ctx.props is undefined" that displays in the style guide instead of the MediaImage component.

Use the old, pre-functional components version of MediaImage

---

src/index.js
vite.config.js

According to the Vue documentation, we need to implement an install() method if other applications wish to use this as a plugin.  See
https://vuejs.org/guide/reusability/plugins.html
Also, the vite config that externalizes the vue dependency doesn't appear to be needed, and it threw an error in approvals.
Helps with #41

Export components as a vue plugin

---

package-lock.json
package.json
src/components/LuxGallery.vue
tests/unit/specs/components/__snapshots__/luxGallery.spec.js.snap
vite.config.js

* Brings the size of dist/lux-styleguidist.mjs from 436.20 kB to 111.31 kB
* Uses vue as a devDependency, rather than a dependency
* Partially reverts PR #43 to externalize Vue in the vite config
* Use VueDraggablePlus, which does not rely on a Vue 2 default import, rather than VueDraggable, which does.
part of https://github.com/pulibrary/approvals/issues/995

Don't package all of Vue inside the bundle

---

README.md
package.json

We were previously having trouble with `np` where npm would ask for an OTP whenever we created a release.  However, it turns out that this is something we can adjust in our npm.js settings, so this PR includes the instructions for changing those settings, and returns to using `np`.
closes #29

Use np for the whole release task

---

tests/unit/specs/components/__snapshots__/luxGallery.spec.js.snap
tests/unit/specs/components/__snapshots__/luxMediaImage.spec.js.snap
tests/unit/specs/components/luxDatePicker.spec.js
tests/unit/specs/components/luxGallery.spec.js
tests/unit/specs/components/luxMediaImage.spec.js
tests/unit/specs/components/luxWrapper.spec.js

Brings us from 6112 lines of warnings to 1248 lines by
- Using the [new vue-test-utils syntax](https://test-utils.vuejs.org/guide/advanced/stubs-shallow-mount) for stubbing child components
- Correcting some mock data that was in the incorrect type

Reduce the amount of warning from running the test suite

---

src/components/LuxInputSelect.vue
tests/unit/specs/components/luxInputSelect.spec.js

The previous version failed to set focus in Vue 3.

LuxInputSelect: Use focusSelect() method with ref instead of a focus prop and attribute

---

src/components/LuxAutocompleteInput.vue
tests/unit/specs/components/luxAutocompleteInput.spec.js

closes #91 
Remove duplicate mounted()
Include attachTo: document.body in the beforeEach() wrapper

Remove duplicate mounted()

---

src/components/LuxDatePicker.vue

This is according to the documentation at https://vcalendar.io/datepicker/slot-content.html#range-inputs
Helps with #107

DatePicker: date range needs to use the inputValue.start or inputValue.end subproperty

---

src/components/LuxDatePicker.vue
tests/unit/specs/components/luxDatePicker.spec.js

Thanks to @maxkadel for identifying the circumstances that cause this error!
closes #107

i107: Don't error if the user enters a partial date range

---

src/components/LuxInputSelect.vue
tests/unit/specs/components/luxInputSelect.spec.js

The Vue 3 migration documentation notes that if you don't declare it, you can get two events when you only expect one: https://v3-migration.vuejs.org/breaking-changes/emits-option.html#migration-strategy
Helps with https://github.com/pulibrary/approvals/issues/1049

Declare the emits used in inputSelect

---

src/components/LuxHyperlink.vue

If it is in a LuxHeading, it inherits pointer-events:none, making it unclickable
Helps with https://github.com/pulibrary/approvals/issues/1055

LuxHyperlink should not have pointer-events turned off via CSS

---

src/components/LuxHyperlink.vue

A small bug I noticed while working on https://github.com/pulibrary/approvals/issues/1055

LuxHyperlink: use the correct syntax for css variables

---

src/components/LuxInputText.vue

closes https://github.com/pulibrary/approvals/issues/1085
adds back the border in the textarea of the inputbox

Slotted css in textarea

---

src/components/LuxDropdownMenu.vue

[Vue 3 changed the names of the custom hooks](https://v3-migration.vuejs.org/breaking-changes/custom-directives#_3-x-syntax), this updates the names to the Vue 3 versions.
Part of https://github.com/pulibrary/approvals/issues/1065

Clicking outside the dropdown menu should close it

---

src/components/logos/LuxLogoLibrary.vue
src/components/logos/LuxLogoLibraryIcon.vue
styleguide.config.js

This fix also makes sure the logos show up in the docs and render in the LuxLibraryHeader component.

Fixes the styleguide:build unterminated template literal syntax error

---

README.md

The docs links were based on the old repo name. This updates it and adds a big link for viewing the Docs at the top.

Updates the docs link in the README

---

src/components/LuxDatePicker.vue
src/components/LuxInputText.vue
tests/unit/specs/components/luxInputText.spec.js

Without this we can't use v-model on LuxInputText, it only does one way binding.

Use the update:value event on input change, to support model binding.

---

package.json
src/components/LuxDatePicker.vue
src/components/LuxInputText.vue
tests/unit/specs/components/luxDatePicker.spec.js

We weren't forwarding enough events to get the v-datepicker widget to work right.
This also tries to fix the range picker, but leaves behind a bug where you have to type it twice for some reason.

Datepicker should not lose text when selecting a date

---

src/components/LuxInputCheckbox.vue
src/components/LuxInputRadio.vue

This update will make sure emits are registered for these components and will fix the radio button behavior found in the Order Manager. Blocking the Figgy LUX/Vue3 upgrade.

Adds emits to radio and checkbox components

---

src/components/LuxLibraryHeader.vue
src/components/LuxLibraryLogo.vue

This allows lux applications to simply import LuxLibraryHeader into a component, and it displays completely, without missing logos or spacers.  This means that lux applications don't have to import all of lux, and can instead tree-shake it for a smaller bundle size.
See https://vuejs.org/guide/components/registration.html#local-registration for more details on local registration.
Closes #217
Helps with pulibrary/static-tables#125

[LuxLibraryHeader] locally register child components

---

src/components/LuxLibraryHeader.vue
src/components/LuxMenuBar.vue
tests/unit/specs/components/__snapshots__/luxMenuBar.spec.js.snap
tests/unit/specs/components/luxMenuBar.spec.js

Prior to this commit, LuxLibraryHeader edited the colors of child LuxMenuBar components according to the value of its theme prop.
This commit moves this CSS to LuxMenuBar, under the control of its own theme prop. This has a few benefits:
* Better separation of concerns (LuxMenuBar is now responsible for its own CSS, rather than LuxLibraryHeader taking responsibility for LuxMenuBar's CSS in certain scenarios).
* These themes are now available to use even if LuxMenuBar is not a child component of LuxLibraryHeader
There is also a tradeoff: if you pass a LuxMenuBar into the LuxLibraryHeader slot and want to use the light theme or shade theme, you will have to specify the theme on both components, instead of just on LuxLibraryHeader.  I could find no usage of the light or shade theme in the …

[LuxMenuBar] refactor deep css in LuxLibraryHeader into a MenuBar theme

---

src/components/LuxLibraryHeader.vue

[#233]Add media query for screens less than 899px to handle the abbr-name in the LibraryHeader

---

src/components/LuxLibraryLogo.vue
src/components/logos/LuxLogoLibraryIcon.vue

Closes #168 
We changed the princeton logo color based on light or dark theme. We added the dark theme color "var(--color-princeton-orange-on-black)" as default.

[#168] recolor logo

---

src/components/LuxInputButton.vue

part of #185
It helps with Subscribe button on focus in LuxLibraryFooter not to change color to blue

[LuxInputButton] #185 remove $color-bleu-de-france-darker; 

---

src/components/LuxLibraryLogo.vue
tests/unit/specs/components/luxLibraryHeader.spec.js

closes #262
part of #https://github.com/pulibrary/allsearch_frontend/issues/313

[LuxLibraryFooter][LuxLibraryHeader] Display the Library Logo and 'Princeton University Library' across all screens

---

README.md

We've finished the migration, so there's no need to devote a large portion of the README to how to do it -- if we want these steps in the future, we can look in old git revisions

[readme] remove migration steps

---

src/assets/styles/variables.css
src/components/LuxLibraryFooter.vue
src/components/LuxLibraryHeader.vue
src/components/LuxMenuBar.vue
src/components/_LuxLibraryContactInfo.vue
src/components/_LuxUniversityAccessibility.vue
src/components/_LuxUniversityCopyright.vue

This makes it consistent with the new WDS website look
closes #266

Use gray-100, rather than rich black, as the background color in header and footer

---

src/components/_LuxUniversityAccessibility.vue
src/components/_LuxUniversityCopyright.vue

[LuxLibraryFooter] Accessibility link and copyright should have same font size as the rest of the footer

---

src/components/_LuxSubscribeNewsletter.vue

Previously, we were using aria-label, but the LuxInputText component doesn't have an aria-label prop, so it was not being properly associated with the input

[LuxSubscribeNewsletter] Use label and hideLabel props to provide an accessible name for the input

---

src/components/_LuxSubscribeNewsletter.vue

LuxInputText doesn't have a prop for aria-required, so it was not getting attached to the input anyway.  Also, the input isn't really required; the form works okay whether you enter your email address or not, so we don't need to tell screen reader users that the field is required.

[LuxSubscribeNewsletter] Don't add aria-required to input

---

src/components/LuxHyperlink.vue
src/components/_LuxUniversityAccessibility.vue
src/components/icons/LuxIconNewTab.vue
src/components/icons/index.js
tests/unit/specs/components/__snapshots__/luxDataTable.spec.js.snap
tests/unit/specs/components/__snapshots__/luxHyperlink.spec.js.snap
tests/unit/specs/components/luxHyperlink.spec.js
tests/unit/specs/components/luxUniversityAccessibility.js

This also adds an SVG icon for opening in a new tab, and adds a prop to LuxHyperlink to toggle the icon on or off.  When the SVG icon is shown, its accessible name is set to 'opens in new tab', to let screen reader users also know about it.
Closes #265

[luxUniversityAccessibility] show that the link opens in a new tab

---

src/components/LuxHyperlink.vue
src/components/LuxInputButton.vue
src/components/LuxInputText.vue
src/components/LuxLibraryFooter.vue
src/components/_LuxSubscribeNewsletter.vue
src/components/_LuxUniversityAccessibility.vue

* Pass boolean true to boolean props, rather than the string true
* Locally register component dependencies, for applications that only use a few lux components and want to tree-shake (e.g. allsearch-frontend)
* Remove some undefined variables/unused props
closes #288

[#288] reduce console warnings

---

src/components/LuxLibraryHeader.vue

This allows the logos in the header and footer to be aligned horizontally. Helps with pulibrary/allsearch_frontend#316

[LuxLibraryHeader] use the same amount of padding as LuxLibraryFooter

---

src/components/LuxLibraryFooter.vue

Let the application main section to handle the margin-bottom.

[LuxLibraryFooter] Remove margin-top from footer. 

---

src/assets/styles/system.scss
src/assets/styles/variables.css
src/components/LuxLibraryFooter.vue
src/components/_LuxLibraryContactInfo.vue
src/components/_LuxLibraryContactInfoOld.vue
src/components/_LuxUniversityAccessibility.vue
src/components/_LuxUniversityCopyright.vue
src/components/logos/LuxLogoUniversityWhite.vue

Update footer to use font-size-base
Update line-height-heading to 1.5
Remove bottom footer padding
Remove pul-logo bottom footer padding
part of https://github.com/pulibrary/lux-design-system/issues/305 part of https://github.com/pulibrary/lux-design-system/issues/306 
part of https://github.com/pulibrary/lux-design-system/issues/309
Update viewport
Update height of LuxLogoUniversityWhite
closes https://github.com/pulibrary/lux-design-system/issues/309

Updates Lux library footer and LuxLogoUniversityWhite

---

src/assets/styles/focus.scss
src/components/LuxCard.vue
src/components/LuxInputButton.vue
src/components/LuxInputText.vue
src/components/LuxLibraryFooter.vue
src/components/LuxLibraryHeader.vue
src/components/LuxLibraryLogo.vue
src/components/LuxMenuBar.vue
src/components/_LuxLibraryContactInfo.vue
src/components/_LuxUniversityAccessibility.vue

This also adds an underline when hovering on links in the header, since there's no other visual indication.
Please review this, I don't work in this space very often!
Closes #303.
Thanks Max for pointing out princeton-focus

Don't show an orange border on hover

---

src/components/LuxMenuBar.vue
tests/unit/specs/components/luxMenuBar.spec.js

Prior to this commit, we only emitted this event when the type was links or buttons.
closes #315

[LuxMenuBar] Emit menu-item-clicked event even when type=main-menu

---

src/components/LuxLibraryFooter.vue
src/components/_LuxUniversityPrivacyNotice.vue
src/components/index.js
tests/unit/specs/components/luxUniversityPrivacyNotice.spec.js

[LuxUniversityPrivacyNotice] Create new component for University Privacy notice
[LuxLibraryFooter] Import LuxUniversityPrivacyNotice in the Library Footer; 
[LuxLibraryFooter] Remove margin-right so that in large screens the new link doesn't wrap the external icon

Create a new University Privacy notice component. Import it in the Library Footer

---

src/components/LuxMenuBar.vue
src/components/_LuxMenuBarLabel.vue
tests/unit/specs/components/__snapshots__/luxMenuBar.spec.js.snap
tests/unit/specs/components/luxMenuBar.spec.js
tests/unit/specs/components/luxMenuBarLabel.spec.js

`unsafe_name` works like the existing name property, except that if it contains some arbitrary HTML, it does not escape it.  The immediate use case for this behavior is the "Bookmarks (4)" menu item in the catalog, which has a span with a specific class around the number that allows Blacklight's javascript to update it as the user adds/removes bookmarks.
This has security implications, since `unsafe_name` bypasses Vue's cross-site scripting protections.  I've added documentation about this (as well as other properties on this object that did not yet have this documentation).
Interestingly, the `buttons` version of LuxMenuBar was already bypassing cross-site scripting protections for the `name` property.  In the interest of consistency and safe defaults, this commit make it match the …

[LuxMenuBar] Add new unsafe_name property to the menu item object

---

docs/adding_lux.md
vite.config.js

This allows us to use Lux's IIFE distribution in <script src=""> without the error: "process is not defined"
See environments variable section under https://vitejs.dev/guide/build.html#library-mode
Related to https://github.com/pulibrary/libapps/issues/26

[Build] Define process.env.NODE_ENV as part of the vite build

---

docs/adding_lux.md

When we first added Lux to LibCal, we mounted it to the page's body, which conflicted with some other javascript that was necessary to successfully make appointments (the appointments would go through, but the user would get confusing error messages and unstyled content).
We found that this issue goes away if you mount separate areas of the DOM as separate Vue apps.
Related to pulibrary/libapps#26

Improve recommendations for adding Lux to a static HTML page

---

src/components/LuxInputText.vue

closes #329 
- [LuxInputText] Remove focus indicator from append-icon. It's not doing anything. 
Currently it shows as:
- Will create a separate ticket for that ^
- [LuxInputText] On hover and focus, override text-decoration to be none;

[LuxInputText] Don't use a text decoration on hover and on focus 

---

docs/lux_usage.md
styleguide.config.js

This gets rid of 1,373(!) color contrast violations, almost all of which come from the code editor.

Use lux variables to style the lux styleguide/documentation

---

docs/design_tokens.md
package.json
src/utils/generateDesignTokenDocs.mjs
styleguide.config.js

This gives us some documentation like we had in Lux versions 4 and earlier (see https://pulibrary.github.io/lux/docs/#/Design%20Tokens), where developers can get a visual of all the color, font size, and spacing design tokens on one page.
Closes #301

[#301] Automatically generate design token documentation on commit and styleguide build

---

src/components/LuxLibraryFooter.vue

Aligning bottom most Princeton logo with the right-most element of the footer
addresses @hackartisan comments on #307

right aligning the footer

---

src/components/LuxMenuBar.vue

Fixes #340
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

[LuxMenuBar] closes dropdowns when you press esc

---

src/components/LuxHyperlink.vue
tests/unit/specs/components/luxHyperlink.spec.js

Similar to links in the Library website and allsearch, the underline is black normally, then becomes orange on hover or focus.
Helps with https://github.com/pulibrary/orangelight/issues/3824

[LuxHyperlink] add an option to underline the link

---

src/components/LuxMenuBar.vue
tests/unit/specs/components/luxMenuBar.spec.js

* aria-expanded was always false before this commit, now it changes based on whether or not the menu is open.
* before this commit, the Esc key did not close the leftmost menu.  With this commit, the Esc key can close any menu.
closes #355

[LuxMenuBar] fix bugs in leftmost menu

---

src/components/LuxLibraryFooter.vue

The library links are not anymore align-content right, so there is no need to push them to the left.

Remove right padding 2rem from the library links ul

---

src/components/LuxLibraryFooter.vue
src/components/LuxUniversityFooter.vue

- Separate university footer from library footer
- Adjust library and university footer contents
closes #360
Screenshots:
University Footer on its own
Library Footer with adjustments

Split out a university footer

---

src/components/LuxUniversityFooter.vue

closes #366 
Also fix bug where there were two hover underlines, one orange and one
white, by using regular link instead of LuxHyperLink
screenshots:
with hover:

Explicitly left-align links in University Footer

---

src/components/LuxDatePicker.vue
src/components/LuxInputCheckbox.vue
src/components/LuxInputRadio.vue

Closes #225
This branch allows the following RSpec test to pass after starting the styleguide locally with `npm run styleguide`:
```
require 'capybara/rspec';
RSpec.configure do |config|
config.include Capybara::DSL
Capybara.default_driver = :selenium
end
RSpec.describe 'LuxInputCheckbox' do
it 'can be checked in capybara' do
visit 'http://localhost:6060/#/Components?id=luxinputcheckbox'
check 'In the clouds'
end
end
RSpec.describe 'LuxInputRadio' do
it 'can be chosen in capybara' do
visit 'http://localhost:6060/#/Components?id=luxinputradio'
choose 'In the clouds'
end
end
```

[LuxInputCheckbox/Radio] Use a visible checkbox and radio, rather than hiding them

---

styleguide.config.js

This resolves a WCAG level A violation (3.1.1 Language of Page).
See [Using the language attribute on the HTML element](https://www.w3.org/WAI/WCAG22/Techniques/html/H57.html) for details
I followed [this configuration example](https://github.com/vue-styleguidist/vue-styleguidist/blob/e4ba2cc8cbc8aa7131a65e8a8e15bf70c4d1bddb/examples/vueds/styleguide.config.js#L21).

[Styleguide] Add language of the page to html element

---

styleguide.config.js

This gives the ability to add an accessible label to the code textareas.

Use CodeMirror, rather than React Simple Code Editor, for editable code examples in the style guide

---

src/components/LuxLibraryHeader.vue
tests/unit/specs/components/luxLibraryHeader.spec.js

This is needed for TigerData, since that application will use a specific logo rather than the default Library Logo.

[LuxLibraryHeader] Allow applications to pass in a custom logo

---

src/components/LuxAlert.vue
src/components/LuxBanner.vue
src/components/LuxCard.vue
src/components/LuxDisclosure.vue
src/components/LuxGridContainer.vue
src/components/LuxGridItem.vue
src/components/LuxHeading.vue
src/components/LuxHyperlink.vue
src/components/LuxInputButton.vue
src/components/LuxLibraryHeader.vue
src/components/LuxSearchBox.vue
src/components/LuxSpacer.vue
src/components/LuxTextStyle.vue
src/components/_LuxCardContent.vue
src/components/_LuxCardHeader.vue
src/components/_LuxCardMedia.vue
tests/unit/specs/components/__snapshots__/luxAlert.spec.js.snap
tests/unit/specs/components/__snapshots__/luxCard.spec.js.snap
tests/unit/specs/components/__snapshots__/luxDataTable.spec.js.snap
tests/unit/specs/components/__snapshots__/luxDropdownMenu.spec.js.snap
tests/unit/specs/components/__snapshots__/luxGridContainer.spec.js.snap
tests/unit/specs/components/__snapshots__/luxGridItem.spec.js.snap
tests/unit/specs/components/__snapshots__/luxHeading.spec.js.snap
tests/unit/specs/components/__snapshots__/luxHyperlink.spec.js.snap
tests/unit/specs/components/__snapshots__/luxTextStyle.spec.js.snap

I used the [vue stylguidist docs](https://vue-styleguidist.github.io/docs/Documenting.html#slots) to learn how to document these.
The documentation appears in the styleguide, within the PROPS & SLOTS disclosures

Add documentation for all slots used in Lux components

---

src/components/LuxAlert.vue
tests/unit/specs/components/luxAlert.spec.js

By default, if an alert is set to autoclear, it disappears after 2 seconds, which is a very short amount of time to read certain messages!
This commit adds a new prop called autoclearSeconds where you can optionally set this to a higher number.  The use case for this is in the catalog, so we can replace the blacklight/bootstrap alert flash message (which waits 5 seconds before disappearing) with LuxAlert.
Also, refactor the autoclear tests to use jest fake timers, so they don't have to wait all those seconds before running their assertions.

[LuxAlert] Add a prop to optionally configure how long before it autoclears

---

src/components/LuxLibraryHeader.vue

This PR fixes the bug. Closes #391 
In the future we may want to look into using a wrapping element to size SVG elements since it's easier to control their size via their containers as explained here: [https://css-tricks.com/scale-svg/](https://css-tricks.com/scale-svg/)
[Discussion can happen here.](https://github.com/pulibrary/lux-design-system/discussions/392)

Fixes bug of hidden menu with mobile LuxLibraryHeader

---

src/components/LuxLibraryHeader.vue
src/components/LuxLibraryLogo.vue
src/components/logos/LuxLogoLibrary.vue

This is a breaking change as it changes the way the Library svg logo is sized. We should not be sizing svg images via dynamic attributes but should instead size them or their containers with css.
Ref #391

Fixes mobile header

---

src/components/LuxSpecialCollectionsFooter.vue

Deleted statement on archival language in the special collections footer

---

src/components/LuxMenuBar.vue
tests/unit/specs/components/luxMenuBar.spec.js

Prior to this commit, if you don't supply an href value for a child menu item, Lux will render an <a> tag without an href.  This is not focusable, so keyboard users will not be able to activate that menu item.
This helps with https://github.com/pulibrary/allsearch_frontend/issues/443, since it allows us to create menu items that are keyboard-focusable that are not links (in this case, they will be buttons that switch between dark mode and light mode).

[LuxMenuBar] If no href is supplied, use a <button> tag instead of an <a> tag

---

src/components/LuxMenuBar.vue

Before this commit, NVDA went into focus mode on menus i.e., keyboard shortcuts did not work.

LuxMenuBar: remove incorrect menu role

---

docs/adding_lux.md
styleguide.config.js

* Vue-styleguidist tries to make interactive versions of code blocks that are js or are in an unspecified language.  These interactive versions then fail when they can't import lux-design-system.  To avoid this, we specify "html" for html blocks and "ts" for javascript blocks.
* Add empty lines around code blocks that need them.
* Also, updates the version of Lux mentioned in these docs to a more current one.
Closes #381

[docs] Include Adding Lux docs in the styleguide site

---

src/components/LuxSearchBox.vue

Helps with https://github.com/pulibrary/allsearch_frontend/issues/497
Previously, the LuxSearchBox was not rounded.  As far as I can tell, this component is used only in Approvals, Lockers, and an upcoming branch for Allsearch Frontend.
Approvals request search:
Allsearch front page (empty)
Allsearch front page (with a search query)
Allsearch search results page (with a search query)

[LuxSearchBox] Rounded design

---

src/components/icons/LuxIconBase.vue
tests/unit/specs/components/__snapshots__/luxDataTable.spec.js.snap

The circle is added if you define the `circleColor` prop.  These are the results of the following example using this patch:
```
<lux-icon-base width="30"  height="30" icon-name="consulting" icon-color="black">
<lux-icon-consulting></lux-icon-consulting>
</lux-icon-base>
<lux-icon-base width="30"  height="30" icon-name="consulting" icon-color="white" circle-color="blue">
<lux-icon-consulting></lux-icon-consulting>
</lux-icon-base>
```
Helps with https://github.com/pulibrary/allsearch_frontend/issues/504

[LuxIconBase] Add an option to put a circle around the icon

---

src/components/LuxBadge.vue

This should help avoid conflicts with any .badge classes that exist already in an application that uses lux.

[LuxBadge] Make class names more specific to lux

---

src/components/icons/LuxIconBookmark.vue
src/components/icons/index.js

Helps with https://github.com/pulibrary/orangelight/issues/4910
Examples from the styleguide docs:

Add a bookmark icon
